### ISSUE TITLE
Display width of some (?) emojis

### ISSUE THREAD

**Issue by gaborcsardi** [brodieG/fansi#62]
I suppose you know about this. Some emojis are apparently printed as double-width in both the macos terminals and in RStudio, but they still have width 1 in `nchar_ctl()`:
```r
❯ fansi::nchar_ctl("\U0001f4e6", type = "width")
[1] 1
```

<img width="253" alt="Screen Shot 2020-02-25 at 10 41 18" src="https://user-images.githubusercontent.com/660288/75240034-9ba4ef80-57bb-11ea-8e11-c1883b3673a1.png">

Do you think it is possible to fix this?

**Comment by gaborcsardi** [comment]
AFAICT from https://unicode.org/Public/UNIDATA/EastAsianWidth.txt in the new standard Emojis are (mostly) wide, so this will resolve by itself at some point, but it would be great to solve it sooner...

**Comment by gaborcsardi** [comment]
https://github.com/brodieG/fansi/blob/7ccb892c8b2ed99ceea30beb683aa94da91c0405/R/fansi-package.R#L133-L137

OK, fair enough...

**Comment by brodieG** [comment]
I think a big thing that's changed is that at least the OSX terminal appears to compute width on these guys correctly now.  I'm 99% certain that was not the case when I wrote the code:

<img width="314" alt="image" src="https://user-images.githubusercontent.com/6105908/75255618-38619000-57b0-11ea-8e07-f79bd12ad1fa.png">

As such there is a much stronger case to make for adding support for this.  I believe Pat Perry's utf8 package has this built in.  How useful is this to you?

**Comment by gaborcsardi** [comment]
Well, if you don't want to "fix" it in fansi, I'll need to hack around it. I think it would be probably simple to do this with a simple lookup table in c. So the utf8 package is not needed just for this.

**Comment by gaborcsardi** [comment]
A related issue is to calculate the correct display width for combined glyphs. Maybe utf8 is correct, idk and I am afk now...

**Comment by gaborcsardi** [comment]
`utf8::utf_width()` seems to be fine for combining characters as well. Pretty cool.
```r
❯ s <- "\U1F477\U1F3FF\u200D\u2640\uFE0F"
❯ nchar(s, type = "width")
[1] 3
❯ fansi::nchar_ctl(s, type = "width")
[1] 3
❯ utf8::utf8_width(s)
[1] 2
❯ cat(s)
👷🏿‍♀️
```

**Comment by brodieG** [comment]
So looking at this a bit more, at least for the wide emojis, I think there is a case to make to r-devel to update from unicode 8 to at least unicode 9 as that is where most of the stuff defaults to [being made wide](https://unicode.org/versions/Unicode9.0.0/#UAX_Changes).  I'm just scratching at the surface, but there is some chance that it's as simple as adding a line to the `table_wcwidth` right [about here](https://github.com/wch/r-source/blob/tags/R-3-6-2/src/main/rlocale_data.h#L1293). 

Obviously I'd need to do a lot more reading to make sure that's correct and there aren't other things that need to happen, but I like the idea of a possible improvement to R's native handling of this stuff.  I'm happy to take the lead on this on r-devel, but it would be useful to know whether you believe this to be crazy / willing to lend some support there (assuming the fix is indeed as simple as I'm hoping it might be).

For combining code points that might be more challenging as AFAICT there is no concept of this in the existing code base.  If this is important then depending on timing I can probably bring in the relevant portions of the underlying [utf8 library](https://github.com/patperry/utf8lite) although I would need to think through the implications.

Finally depending on your urgency we can come up with varying degrees of shortcuts to get something that works sooner.

I do agree that, given the world at large has moved on from Unicode 8, fansi should address this at some point in the not too distant future.

**Comment by gaborcsardi** [comment]
Yeah, ideally this would be in R core, but until then maybe fansi can just use the utf8 R package, which is great!

**Comment by gaborcsardi** [comment]
An alternative for R core would be to rely on the ICU, I am sure that that gets it right as well. But of course then the ICU would be compulsory and they probably don't want that, and also the result depends on the ICU version.

**Comment by brodieG** [comment]
What's your timeframe here?  I don't want to just pull in utf8 as a dependency (explicit or implicit) without thinking this through, especially if its just for the width calculation.  I've got a few other things on my plate atm so I'm thinking I won't get to this for at least one month, though maybe I'll start the r-devel discussion earlier to see what direction that goes in.

**Comment by gaborcsardi** [comment]
That's fine, I can work around it.

**Comment by brodieG** [comment]
Ok, I'll leave this open as I think fansi should do this properly eventually.

**Comment by gaborcsardi** [comment]
Btw. it is not a one line change in base R, because several ranges need to be updated. E.g. this is wrong as well:

```r
❯ cat("\u2728")
✨
❯ nchar("\u2728", type = "width")
[1] 1
❯ utf8::utf8_width("\u2728")
[1] 2
❯ stringi::stri_width("\u2728")
[1] 2
```

Here is some code that parses the spec (the 12.1.0 one currently) and checks what R thinks about the widths of the wide characters:

```r
tab <- read.delim(
  stringsAsFactors = FALSE,
  "https://unicode.org/Public/UNIDATA/EastAsianWidth.txt",
  comment.char = "#",
  sep = ";",
  strip.white = TRUE,
  header = FALSE
)

# Keep wide ones
wide <- tab$V1[tab$V2 == "W"]
first <- sub("\\.\\..*$", "", wide)
test <- sapply(parse(text = paste0('"', "\\U", first, '"')), eval)
nchar(test, type = "width")
```

```r
#>   [1] 2 1 2 2 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2
#>  [38] 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 0 0 2 2 2
#>  [75] 2 2 2 2 2 2 0 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 1 2
#> [112] 1 2 2 2 2 1 2 2 1 2 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
#> [149] 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
#> [186] 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
#> [223] 1 2 1 1 1 1 1 1 1 1 1 2 1 1 2
```

This only tests the first character of every range.

**Comment by gaborcsardi** [comment]
@brodieG Do you want to propose the Unicode 8 -> Unicode 9 (or maybe an even newer version) change on R-devel? I think if we hurry it might still make it into 4.0.0, which would be awesome.

But I have no idea if anything else must be updated, in addition to that lookup table.

**Comment by brodieG** [comment]
I just panicked for a moment b/c I thought 4.0.0 was for 2/29, but that's 3.6.3.

I have 3 packages failing on CRAN that I need to fix, but I think I've got the hard issues dealt with, so I can make this next in line and probably have it out to r-devel by Monday.

If you want to move faster and are willing to go r-devel do feel free to do so.  Otherwise I will work on it on the weekend (and will be happy to).  There are other issues to resolve (e.g. are there locale issues that need to be handled - that table has different columns for locales), and confirm that updating the table is really the only issue.

Unfortunately I have a day job so I can only allocate so much time each day to FOSS.

**Comment by gaborcsardi** [comment]
No rush. :) I worked around the wide ones using a silly doubling trick: https://github.com/r-lib/cli/pull/139/files

**Comment by gaborcsardi** [comment]
Btw. yet another way to support this would be to allow supplying a pre-computed char width vector to `strwrap*()`. Then I could pre-compute the widths with utf8 and pass it to fansi. 

Ideally I would precompute the prefix lengths, i.e. the display width after each Unicode character. It is very easy to modify utf8 to do this. Then using this fansi can easily use the correct display width in `strwrap*()`. It is a bit of a hack, and then `strwrap*()` and `fansi::nchar*(..., type = "width")` will be inconsistent, which is quite ugly.

**Comment by brodieG** [comment]
So looked at this a bit more.  I think the update to the table is conceptually simple, but also not completely straightforward as BDR (or someone before him) went to quite a bit of effort tracking down locale specific widths for the east asian ambiguous sets, AND how they vary for win32.  So this will require some range splitting and text munging.  Nothing crazy, but more work than just adding rows.

In re ICU, looks like ICU is already in use by R when available (seems to be most platforms except maybe windows; see `?icuSetCollate`).  It is however optional so whatever we do with ICU will need some fallback mechanism anyway.  Additionally one big problem is that OS X does not appear to provide the requisite headers despite making the library available.  For example, for the collation stuff R defines its [own copy of the subset of the headers it needs][1]. 

If we go ahead with ICU probably what we want is the [UBreakIterator][2], but given how many headers that brings in I'm a little worried that could be a bit of a project.  If tools exist to extract the relevant header info then maybe that's not too bad, but I don't have experience doing this type of thing.  UBreakIterator will compute the grapheme boundaries to deal with the combining emoji and similar.

Additionally, I'm having a hard time (granted, haven't looked exhaustively) finding a function that computes grapheme width in ICU.  I get a sense that ICU doesn't see that as its responsibility, at least based on looking at things [like this][3].  So we might not be able to just plop in an existing function, but instead would have to fetch each grapheme and compute its width, presumably from the width of the first code point (or figure out the rules that govern this).

I think probably the best course of action is to:

1. Generate an updated table to replace the existing R one and propose it as a patch.
2. Give up (for now) on the idea of getting R to correctly compute combining graphemes.
3. Port to `fansi` the grapheme computations from `utf8` for use once the width tables are updated in R.
4. (maybe) if folks are excited by the idea, also port them to R

[1]: https://github.com/wch/r-source/blob/tags/R-3-6-2/src/main/util.c#L1942
[2]: https://unicode-org.github.io/icu-docs/apidoc/released/icu4c/ubrk_8h.html
[3]: http://userguide.icu-project.org/boundaryanalysis#TOC-Word-wrap-a-document-C-only-:

**Comment by brodieG** [comment]
So this was a bit more of a pain than I expected, but here is a (not yet thoroughly checked) version of the updated table.

Unfortunately I need to read the Unicode docs more thoroughly to understand how all this interacts before I go ahead and propose a patch.  So it's going to take a bit longer to get this sent out.

[rlocale_diff.txt](https://github.com/brodieG/fansi/files/4304180/rlocale_diff.txt)

**Comment by brodieG** [comment]
So this took a lot longer than I expected (pandemic didn't help) so its likely out of the question for 4.0, but we could try to get it into 4.1.  I do worry though that it might get ignored by the powers that be.  @gaborcsardi are you okay vocally supporting this proposal on r-devel?  Any feedback?

* [Intended submission e-mail][1] (maybe I'll do this directly on r-bugs and e-mail a shorter version to r-devel)
* [Patch][2]
* [Full details][3]

[1]: https://github.com/brodieG/char-width/blob/v0.1.0/doc/uni-submit.md
[2]: https://github.com/brodieG/char-width/blob/v0.1.0/patches/patch-rlocale-data.txt
[3]: https://github.com/brodieG/char-width/tree/v0.1.0

**Comment by brodieG** [comment]
This is now [partially resolved](https://bugs.r-project.org/bugzilla/show_bug.cgi?id=17781).

Dealing with graphemes remains an issue.

**Comment by brodieG** [comment]
See #66 for grapheme width.

**Comment by gaborcsardi** [comment]
Cool, thanks!
