### ISSUE TITLE
Test has problems to find unitizer/_pre/lorem.data/lorem.cn.phrases.RDS

### ISSUE THREAD

**Issue by tillea** [brodieG/fansi#76]
Hi,
I tried to update the Debian packaged version of fansi.  We are running this [test](https://salsa.debian.org/r-pkg-team/r-cran-fansi/-/blob/master/debian/tests/run-unit-test) which is basically doing

    cd tests
    LC_ALL=C R --no-save < run.R

The test unfortunately is running into a failure which you can inspect [in the full log](https://salsa.debian.org/r-pkg-team/r-cran-fansi/-/jobs/4946845#L4112) where it fails with

    In gzfile(file, "rb") :
      cannot open compressed file 'unitizer/_pre/lorem.data/lorem.cn.phrases.RDS', probable reason 'No such file or directory'

The reason is simply that at the time of processing this code the current working directory is `.../special`.  I did not dived into the full code but this simple [patch](https://salsa.debian.org/r-pkg-team/r-cran-fansi/-/blob/master/debian/patches/move_to_correct_dir.patch) injecting some

    setwd("..")

right before the affected line is working around this issue.  I guess you want to use some proper fix adding that line whereever it belongs logically in your code but for the moment it helped passing the test.
Kind regards, Andreas.

**Comment by brodieG** [comment]
Thanks for reporting the issue @tillea .  I'll investigate at some point later this week.

**Comment by brodieG** [comment]
Ok, so I'm able to reproduce by running the tests outside of the original package folder structure.  For better or worse CRAN always runs tests inside a copy of the entire package, at the same relative positioning.  `unitizer` (test framework) uses this known folder structure to orient itself.

Strictly speaking WRE doesn't document this must be the case, so your use case is valid and in theory should be supported.  Nonetheless, given that this is the first time this has come up, and you have found a simple work-around via the patch, I'm not going to address this in the near term.  I will open an issue at `unitizer` as that's where the problem truly is.

**Comment by tillea** [comment]
Thanks a lot for tracking this down.  I confirm, I'm not in a hurry since the workaround fits my needs.  More a general question:  Where can I find the test log at CRAN?  Maybe I will be able to help a bit more in future.

**Comment by brodieG** [comment]
The CRAN repository test logs are available [on CRAN](https://cran.r-project.org/web/checks/check_summary_by_package.html) if you click on e.g. the "OK" or "ERROR" or whatever status link corresponds to each tested platform.  They might not show all details though.
